#!/usr/bin/env bash
set -euo pipefail

profile="${1:-}"

case "${profile}" in
  release_matrix)
    cat <<'EOF'
XT_GATE_SKIP_BUILD=1
XT_GATE_SKIP_SPLIT_AUDIT_CONTRACT=1
XT_GATE_SKIP_XT_READY_CONTRACT=1
XT_GATE_VALIDATE_PROJECT_GOVERNANCE=0
XT_GATE_VALIDATE_RELEASE_EVIDENCE_MATRIX=0
EOF
    ;;
  split_flow_policy)
    cat <<'EOF'
XT_GATE_SKIP_BUILD=1
XT_GATE_SKIP_XT_READY_CONTRACT=1
XT_GATE_SKIP_XT_READY_EXECUTABLE=1
XT_GATE_VALIDATE_PROJECT_GOVERNANCE=0
XT_GATE_VALIDATE_RELEASE_EVIDENCE_MATRIX=0
XT_GATE_VALIDATE_SPLIT_FLOW_RUNTIME_POLICY=0
XT_GATE_AUTO_PREPARE_RELEASE_EVIDENCE=0
EOF
    ;;
  fast_check_matrix)
    cat <<'EOF'
XT_GATE_RELEASE_PRESET=0
XT_GATE_SKIP_BUILD=1
XT_GATE_SKIP_XT_READY_CONTRACT=1
XT_GATE_SKIP_XT_READY_EXECUTABLE=0
XT_GATE_VALIDATE_PROJECT_GOVERNANCE=0
XT_GATE_VALIDATE_RELEASE_EVIDENCE_MATRIX=1
XT_GATE_VALIDATE_SPLIT_FLOW_RUNTIME_POLICY=0
XT_GATE_AUTO_PREPARE_RELEASE_EVIDENCE=0
EOF
    ;;
  fast_check_baseline)
    cat <<'EOF'
XT_GATE_RELEASE_PRESET=0
XT_GATE_SKIP_BUILD=1
XT_GATE_SKIP_XT_READY_CONTRACT=1
XT_GATE_SKIP_XT_READY_EXECUTABLE=0
XT_GATE_VALIDATE_PROJECT_GOVERNANCE=0
XT_GATE_VALIDATE_RELEASE_EVIDENCE_MATRIX=0
XT_GATE_VALIDATE_SPLIT_FLOW_RUNTIME_POLICY=0
XT_GATE_AUTO_PREPARE_RELEASE_EVIDENCE=0
EOF
    ;;
  *)
    echo "[xt-nested-gate-profile] unknown profile: ${profile}" >&2
    exit 2
    ;;
esac
