import Foundation
import Testing
@testable import XTerminal

struct SupervisorConversationComposerSupportTests {
    private var sampleAttachment: AXChatAttachment {
        AXChatAttachment(
            displayName: "notes.txt",
            path: "/tmp/notes.txt",
            kind: .file,
            scope: .attachmentReadOnly
        )
    }

    @Test
    func syncedDraftOnlyChangesWhenExternalInputActuallyDiffers() {
        #expect(
            SupervisorConversationComposerSupport.syncedDraft(
                currentDraft: "hello",
                externalInput: "hello"
            ) == "hello"
        )
        #expect(
            SupervisorConversationComposerSupport.syncedDraft(
                currentDraft: "hello",
                externalInput: "hello world"
            ) == "hello world"
        )
    }

    @Test
    func syncedInputOnlyChangesWhenDraftActuallyDiffers() {
        #expect(
            SupervisorConversationComposerSupport.syncedInput(
                currentInput: "draft",
                draft: "draft"
            ) == "draft"
        )
        #expect(
            SupervisorConversationComposerSupport.syncedInput(
                currentInput: "",
                draft: "draft"
            ) == "draft"
        )
    }

    @Test
    func submissionTransitionTrimsPayloadAndClearsComposer() {
        let transition = SupervisorConversationComposerSupport.submissionTransition(
            draft: "  continue this task  \n"
        )

        #expect(
            transition == SupervisorConversationComposerTransition(
                payload: "continue this task",
                nextDraft: "",
                nextInput: ""
            )
        )
        #expect(
            SupervisorConversationComposerSupport.submissionTransition(draft: "   \n") == nil
        )
    }

    @Test
    func autoSendVoiceTransitionRequiresAutoSendAndClearsComposer() {
        #expect(
            SupervisorConversationComposerSupport.autoSendVoiceTransition(
                recognized: "批准这个 grant",
                autoSendVoice: false
            ) == nil
        )
        #expect(
            SupervisorConversationComposerSupport.autoSendVoiceTransition(
                recognized: "  批准这个 grant  ",
                autoSendVoice: true
            ) == SupervisorConversationComposerTransition(
                payload: "批准这个 grant",
                nextDraft: "",
                nextInput: ""
            )
        )
    }

    @Test
    func attachmentsOnlySubmissionUsesAutoGeneratedAttachmentPrompt() {
        let attachment = sampleAttachment
        let transition = SupervisorConversationComposerSupport.submissionTransition(
            draft: "   ",
            attachments: [attachment]
        )

        #expect(
            transition == SupervisorConversationComposerTransition(
                payload: "请先阅读并理解我附带的文件。",
                attachments: [attachment],
                nextDraft: "",
                nextInput: "",
                nextAttachments: []
            )
        )
    }

    @Test
    func applyingImportContinuationKeepsUserDraftUnchanged() {
        let continued = SupervisorConversationComposerSupport.applyingImportContinuation(
            draft: "先保持现有说明",
            continuation: AXChatImportContinuationSuggestion(
                headline: "导入完成",
                detail: "detail",
                placementHint: "placement",
                linkedFilesHint: "linked",
                suggestedPrompt: "请继续处理导入后的项目内副本。",
                importedAttachmentPaths: ["/tmp/project/Imported Attachments/notes.txt"]
            )
        )

        #expect(continued == "先保持现有说明")
    }

    @Test
    func continueAndSendTransitionSendsOnlyUserDraft() {
        let attachment = AXChatAttachment(
            displayName: "Worker.swift",
            path: "/tmp/project/Imported Attachments/Worker.swift",
            relativePath: "Imported Attachments/Worker.swift",
            kind: .file,
            scope: .projectWorkspace
        )
        let continuation = AXChatImportContinuationSuggestion(
            headline: "代码文件已进入项目",
            detail: "detail",
            placementHint: "placement",
            linkedFilesHint: "linked",
            suggestedPrompt: "请先判断 `Imported Attachments/Worker.swift` 在项目里的角色，再继续完成接入。",
            importedAttachmentPaths: [attachment.path]
        )

        let transition = SupervisorConversationComposerSupport.continueAndSendTransition(
            draft: "已有说明",
            attachments: [attachment],
            continuation: continuation
        )

        #expect(transition?.payload == "已有说明")
        #expect(transition?.attachments == [attachment])
        #expect(transition?.nextDraft == "")
        #expect(transition?.nextInput == "")
        #expect(transition?.nextAttachments == [])
    }
}
